use_frameworks!

platform :ios, '8.0'

target 'ZGpNewCommon_Example' do
  pod 'ZGpNewCommon', :path => '../'

  target 'ZGpNewCommon_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
